spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
server:
  servlet:
    context-path: /restaurant/api/v1
springdoc:
  swagger-ui:
    path: /swagger-ui